# Generated by Django 3.1.2 on 2020-12-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0004_publicacao_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user/image/profile-pic.png', null=True, upload_to='media/images'),
        ),
    ]
